- hosts: localhost
  tasks:
    - add_host:
        name: "g2-nuc-1"

    - known_host:
        name: "g2-nuc-1"
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEpubS0vKuFJPbLB/Bf60gd1d2zLMUS/BIRXn91AEeYFkLId93U0qjCm5suGM0nauNgC7PRuTS0PJDvhWPOlGi/Ry+XGH4rc4o+o98M78/NkVdv5P9ibCvFlNHETWLpl/XB4Nrb3E7CktzQ+W1uVgc1THc9OWFuy1iG2FxGXlhminhKwHqwRPQl+0uRte9Piyojs9mh/vsY7eUNOpOjNT2pg8+7n7xsrU76GSLpowMnzxhoEkMXeTfl/CkkLU+Nw0dZTd5FetEE6jAnhPsFI1luQhxQ2FXQ6NvgtSaFcXnxTuNWyPwBjqvH+7hpluEgzaNEZtlsLEPZlgyKsnaDDJ6fLgohHYhV1xUkMSc6zUBexFSI3QPQaKx/ptIbhDhAbi40rMAqoiVTiE6joP1kMTnxBV2+lPNVe3WP2vUoJA4eB//9DMOIcHADa2kgm+xhOmt/jG08FpCEOCztu3IIBdfGkEOqEW5HWClPjYUncxD04BJOjieoy0sQnC4Vdlrop0= g262@g2-nuc-1"

- job:
    name: cnf-cert-test
    run: 
      - playbooks/install.yaml


- project:
    check:
      jobs:
        - cnf-cert-test
    gate:
      jobs:
        - cnf-cert-test
