- job:
    name: no-op
    description: Run github pr integration test
    run: playbooks/no-op.yaml

- project:
    check:
      jobs:
        - no-op
        - noop
    gate:
      jobs:
        - no-op
